In [165]:
import numpy as np
#importing numpy and using it as np

# **Step 1️⃣ Create Dataset (40 employees)**

In [177]:
#creating a sample data
# Columns = [ID, Age, Salary (₹), Performance Score (0–10)]
# Rows = individual employee data
data = np.array([
    [1, 22, 35000, 7],
    [2, 25, 42000, 8],
    [3, 28, 50000, 6],
    [4, 35, 60000, 9],
    [5, 40, 75000, 7],
    [6, 30, 45000, 5],
    [7, 26, 52000, 8],
    [8, 29, 58000, 6],
    [9, 32, 49000, 9],
    [10, 45, 80000, 8],
    [11, 36, 72000, 7],
    [12, 27, 48000, 6],
    [13, 34, 65000, 9],
    [14, 31, 47000, 5],
    [15, 39, 69000, 7],
    [16, 42, 85000, 8],
    [17, 33, 56000, 6],
    [18, 29, 53000, 7],
    [19, 38, 77000, 9],
    [20, 41, 90000, 10],
    # Adding more employees with missing/erroneous values
    [21, 27, np.nan, 8],       # Missing salary
    [22, 30, 61000, np.nan],   # Missing score
    [23, 44, 0, 9],            # Salary wrongly entered as 0
    [24, 50, 120000, 11],      # Score > 10 (error)
    [25, 23, 40000, 6],
    [26, 26, 51000, 8],
    [27, 29, np.inf, 7],       # Salary recorded as infinity
    [28, 37, 70000, 6],
    [29, 35, -np.inf, 9],      #Salary recorded as negetive infinite
    [30, 31, 48000, 5],
    [31, 40, 75000, 8],
    [32, 39, 71000, 7],
    [33, 28, 55000, 6],
    [34, 32, 49000, 7],
    [35, 34, 62000, 8],
    [36, 43, 81000, 9],
    [37, 41, 88000, 8],
    [38, 46, 95000, 10],
    [39, 48, np.nan, 9],       # Missing salary again
    [40, 29, 53000, 6]
])

np.set_printoptions(suppress=True, precision=2)  # suppress scientific notation, 2 decimal places

# Now print your data
print(data)

[[     1.     22.  35000.      7.]
 [     2.     25.  42000.      8.]
 [     3.     28.  50000.      6.]
 [     4.     35.  60000.      9.]
 [     5.     40.  75000.      7.]
 [     6.     30.  45000.      5.]
 [     7.     26.  52000.      8.]
 [     8.     29.  58000.      6.]
 [     9.     32.  49000.      9.]
 [    10.     45.  80000.      8.]
 [    11.     36.  72000.      7.]
 [    12.     27.  48000.      6.]
 [    13.     34.  65000.      9.]
 [    14.     31.  47000.      5.]
 [    15.     39.  69000.      7.]
 [    16.     42.  85000.      8.]
 [    17.     33.  56000.      6.]
 [    18.     29.  53000.      7.]
 [    19.     38.  77000.      9.]
 [    20.     41.  90000.     10.]
 [    21.     27.     nan      8.]
 [    22.     30.  61000.     nan]
 [    23.     44.      0.      9.]
 [    24.     50. 120000.     11.]
 [    25.     23.  40000.      6.]
 [    26.     26.  51000.      8.]
 [    27.     29.     inf      7.]
 [    28.     37.  70000.      6.]
 [    29.     35.   

# **Step 2️⃣ Handle Errors & Missing Data**

In [178]:
#creating the vews
salarys = data[:,2]
scores = data[:,3]
print(salarys)
print(scores)

[ 35000.  42000.  50000.  60000.  75000.  45000.  52000.  58000.  49000.
  80000.  72000.  48000.  65000.  47000.  69000.  85000.  56000.  53000.
  77000.  90000.     nan  61000.      0. 120000.  40000.  51000.     inf
  70000.    -inf  48000.  75000.  71000.  55000.  49000.  62000.  81000.
  88000.  95000.     nan  53000.]
[ 7.  8.  6.  9.  7.  5.  8.  6.  9.  8.  7.  6.  9.  5.  7.  8.  6.  7.
  9. 10.  8. nan  9. 11.  6.  8.  7.  6.  9.  5.  8.  7.  6.  7.  8.  9.
  8. 10.  9.  6.]


In [179]:
#lets replace inf/-inf with possible max and min salary
print(f"Before Replacing the inf/-inf values from salaryes to max and min {salarys}")
print()
finite = salarys[np.isfinite(salarys)]
max_valid_salary = np.max(finite)
min_valid_salary = np.min(finite)
salarys[np.isposinf(salarys)] = max_valid_salary
salarys[np.isneginf(salarys)] = min_valid_salary
print(f"max valid salary: {max_valid_salary}")
print(f"min valid salary: {min_valid_salary}")
print()
print(f"After Replacing the inf/-inf values from salaryes to max and min {salarys}")


Before Replacing the inf/-inf values from salaryes to max and min [ 35000.  42000.  50000.  60000.  75000.  45000.  52000.  58000.  49000.
  80000.  72000.  48000.  65000.  47000.  69000.  85000.  56000.  53000.
  77000.  90000.     nan  61000.      0. 120000.  40000.  51000.     inf
  70000.    -inf  48000.  75000.  71000.  55000.  49000.  62000.  81000.
  88000.  95000.     nan  53000.]

max valid salary: 120000.0
min valid salary: 0.0

After Replacing the inf/-inf values from salaryes to max and min [ 35000.  42000.  50000.  60000.  75000.  45000.  52000.  58000.  49000.
  80000.  72000.  48000.  65000.  47000.  69000.  85000.  56000.  53000.
  77000.  90000.     nan  61000.      0. 120000.  40000.  51000. 120000.
  70000.      0.  48000.  75000.  71000.  55000.  49000.  62000.  81000.
  88000.  95000.     nan  53000.]


In [180]:
#lets replace Nan and 0's with mean.
print(f"Before Replacing the Nan values from salaryes to mean {salarys}")
print()
temp_salaries = salarys.copy()
temp_salaries[temp_salaries == 0] = np.nan
salary_mean = np.nanmean(temp_salaries)

print(f"salarys mean: {salary_mean}")
salary_mean = np.round(salary_mean,2)
print(f"salarys mean after rounding: {salary_mean}")
salarys[np.isnan(salarys)] = salary_mean
salarys[salarys == 0] = salary_mean
print()
print(f"After Replacing the Nan values from salaryes to mean {salarys}")

#Updating it in original data
data[:,2] = salarys

Before Replacing the Nan values from salaryes to mean [ 35000.  42000.  50000.  60000.  75000.  45000.  52000.  58000.  49000.
  80000.  72000.  48000.  65000.  47000.  69000.  85000.  56000.  53000.
  77000.  90000.     nan  61000.      0. 120000.  40000.  51000. 120000.
  70000.      0.  48000.  75000.  71000.  55000.  49000.  62000.  81000.
  88000.  95000.     nan  53000.]

salarys mean: 65194.444444444445
salarys mean after rounding: 65194.44

After Replacing the Nan values from salaryes to mean [ 35000.    42000.    50000.    60000.    75000.    45000.    52000.
  58000.    49000.    80000.    72000.    48000.    65000.    47000.
  69000.    85000.    56000.    53000.    77000.    90000.    65194.44
  61000.    65194.44 120000.    40000.    51000.   120000.    70000.
  65194.44  48000.    75000.    71000.    55000.    49000.    62000.
  81000.    88000.    95000.    65194.44  53000.  ]


In [181]:
#Fix scores > 10 → clip to 10
print(f"scores before clip: {scores}")
scores = np.clip(scores, 0, 10)
print()
print(f"scores after clip: {scores}")


scores before clip: [ 7.  8.  6.  9.  7.  5.  8.  6.  9.  8.  7.  6.  9.  5.  7.  8.  6.  7.
  9. 10.  8. nan  9. 11.  6.  8.  7.  6.  9.  5.  8.  7.  6.  7.  8.  9.
  8. 10.  9.  6.]

scores after clip: [ 7.  8.  6.  9.  7.  5.  8.  6.  9.  8.  7.  6.  9.  5.  7.  8.  6.  7.
  9. 10.  8. nan  9. 10.  6.  8.  7.  6.  9.  5.  8.  7.  6.  7.  8.  9.
  8. 10.  9.  6.]


In [182]:
#Fix Nan score by rounding the mean
print(f"scores before rounding: {scores}")
mean_score = np.nanmean(scores)
print(f"mean score: {mean_score}")
scores[np.isnan(scores)] = np.round(mean_score)
print(f"scores after rounding the mean: {scores}")
#Updating in orginal data
data[:,3] = scores

scores before rounding: [ 7.  8.  6.  9.  7.  5.  8.  6.  9.  8.  7.  6.  9.  5.  7.  8.  6.  7.
  9. 10.  8. nan  9. 10.  6.  8.  7.  6.  9.  5.  8.  7.  6.  7.  8.  9.
  8. 10.  9.  6.]
mean score: 7.512820512820513
scores after rounding the mean: [ 7.  8.  6.  9.  7.  5.  8.  6.  9.  8.  7.  6.  9.  5.  7.  8.  6.  7.
  9. 10.  8.  8.  9. 10.  6.  8.  7.  6.  9.  5.  8.  7.  6.  7.  8.  9.
  8. 10.  9.  6.]


In [183]:
#checking the new clean data
print(data)

[[     1.       22.    35000.        7.  ]
 [     2.       25.    42000.        8.  ]
 [     3.       28.    50000.        6.  ]
 [     4.       35.    60000.        9.  ]
 [     5.       40.    75000.        7.  ]
 [     6.       30.    45000.        5.  ]
 [     7.       26.    52000.        8.  ]
 [     8.       29.    58000.        6.  ]
 [     9.       32.    49000.        9.  ]
 [    10.       45.    80000.        8.  ]
 [    11.       36.    72000.        7.  ]
 [    12.       27.    48000.        6.  ]
 [    13.       34.    65000.        9.  ]
 [    14.       31.    47000.        5.  ]
 [    15.       39.    69000.        7.  ]
 [    16.       42.    85000.        8.  ]
 [    17.       33.    56000.        6.  ]
 [    18.       29.    53000.        7.  ]
 [    19.       38.    77000.        9.  ]
 [    20.       41.    90000.       10.  ]
 [    21.       27.    65194.44      8.  ]
 [    22.       30.    61000.        8.  ]
 [    23.       44.    65194.44      9.  ]
 [    24.  

# **Step 3️⃣ Analysis After Cleaning**


**1.   Shows how performance changes with salary**




* Performance tends to increase with salary, but some low-salary employees still perform well.

* This analysis can help identify underpaid high performers or assess salary vs performance trends  







In [184]:
#Average Performance by Salary Bracket

low = salarys < 50000;
mid = (salarys >= 50000) & (salarys <= 75000);
high = salarys > 75000;

print("Avg Performance Low Salary:", np.round(np.mean(scores[low]),2))
print("Avg Performance Mid Salary:", np.round(np.mean(scores[mid]),2))
print("Avg Performance High Salary:",np.round(np.mean(scores[high]),2))


Avg Performance Low Salary: 6.44
Avg Performance Mid Salary: 7.45
Avg Performance High Salary: 8.78





 **2.   Top 5 Employees by Weighted Score**

 * The idea is to rank employees not just by salary or performance individually, but by a combination of both. This simulates a real-world scenario where companies may value both how much someone earns (experience/seniority) and how well they perform.



*   Weighted ranking helps highlight overall top talent, considering both compensation and performance.





In [185]:
#1)Normalize Salary and Score:
#To combine them fairly, we scale both between 0 and 1:

salary_norm = (salarys - np.min(salarys)) / (np.max(salarys) - np.min(salarys))
score_norm = scores / 10

#2)Combine with Weights:
#Give importance to salary vs performance.

#Example: 60% weight for salary, 40% weight for performance:

combined = 0.6*salary_norm + 0.4*score_norm


#3)Use np.argsort to rank all employees by this combined metric:

ranked_employees = np.argsort(combined)

top5 = data[ranked_employees[-5:]]
print(top5)



[[    37.     41.  88000.      8.]
 [    20.     41.  90000.     10.]
 [    38.     46.  95000.     10.]
 [    27.     29. 120000.      7.]
 [    24.     50. 120000.     10.]]




**3.   Average Age by Salary Bracket**


*   Insight: See if older employees are in higher salary brackets.




In [186]:
# Define salary brackets
brackets = [0, 50000, 70000, 90000, 120000]
labels = ["0-50k", "50k-70k", "70k-90k", "90k-120k"]

for i in range(len(brackets)-1):
    #mask for each bracket
    mask = (data[:,2] >= brackets[i]) & (data[:,2] < brackets[i+1])
    #mean  of age in each mask
    avg_age = np.mean(data[mask][:,1])
    print(f"Average age for salary {labels[i]}: {avg_age:.2f}")


Average age for salary 0-50k: 28.11
Average age for salary 50k-70k: 32.59
Average age for salary 70k-90k: 40.10
Average age for salary 90k-120k: 43.50




 **4. High Performers in Low Salary**


*   Insight: Find employees who perform well but are underpaid.





In [187]:
#setting the range for low salary and high performance
high_performance = 8
low_salary = 60000
#creating the mask where a employee salary is < 60000 and has a perforamnce score >= 8
mask = (data[:,3] >= high_performance) & (data[:,2] < low_salary)
print(f"this empolyees deserves better: {data[mask]}")

this empolyees deserves better: [[    2.    25. 42000.     8.]
 [    7.    26. 52000.     8.]
 [    9.    32. 49000.     9.]
 [   26.    26. 51000.     8.]]




**5.   Salary vs Performance Correlation**


*  Insight: See if higher salaries actually correspond to better performance.




In [188]:
#setting up the views
salary = data[:,2]
performance = data[:,3]
#finding the Correlation coeffecient range btw(0,1)
Correlation = np.corrcoef(salary,performance)[0,1]
print(f"Correlation: {Correlation}")

Correlation: 0.519757774672183
